---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: WS4406
    inherits: 
    description: 
  fields:
  - name:
      value: WS4406
  - instanceid:
      value: i-67125a81
  - taskid1:
      value: import-i-fgtrvrfz
  - volumeid2:
      value: vol-b59b6eaa
  - taskid2:
      value: import-vol-fh91u8iw
  - volumeid3:
      value: vol-fa9b6ee5
  - taskid3:
      value: import-vol-ffmv6kxq
