---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: Default
    inherits: 
    description: 
  fields:
  - server:
      value: ipam.example.com
  - context:
      value: "/phpipam"
  - api_key:
      value: cloudforms
  - api_token:
      value: 0123456789abcdef0123456789abcdef
