---
object_type: class
version: 1.0
object:
  attributes:
    description: State Machines
    display_name: 
    name: VMMigrate
    type: 
    inherits: 
    visibility: 
    owner: 
  schema:
  - field:
      aetype: state
      name: ShutdownVM
      display_name: 
      datatype: string
      priority: 1
      owner: 
      default_value: 
      substitute: true
      message: create
      visibility: 
      collect: 
      scope: 
      description: 
      condition: 
      on_entry: 
      on_exit: 
      on_error: 
      max_retries: '100'
      max_time: 
  - field:
      aetype: state
      name: ExportVM
      display_name: 
      datatype: string
      priority: 2
      owner: 
      default_value: 
      substitute: true
      message: create
      visibility: 
      collect: 
      scope: 
      description: 
      condition: 
      on_entry: 
      on_exit: 
      on_error: 
      max_retries: '100'
      max_time: 
  - field:
      aetype: state
      name: EmailExportVM
      display_name: 
      datatype: string
      priority: 3
      owner: 
      default_value: 
      substitute: true
      message: create
      visibility: 
      collect: 
      scope: 
      description: 
      condition: 
      on_entry: 
      on_exit: 
      on_error: 
      max_retries: '100'
      max_time: 
  - field:
      aetype: state
      name: ImportInstance
      display_name: 
      datatype: string
      priority: 4
      owner: 
      default_value: 
      substitute: true
      message: create
      visibility: 
      collect: 
      scope: 
      description: 
      condition: 
      on_entry: 
      on_exit: 
      on_error: 
      max_retries: '100'
      max_time: 
  - field:
      aetype: state
      name: CheckImportInstance
      display_name: 
      datatype: string
      priority: 5
      owner: 
      default_value: 
      substitute: true
      message: create
      visibility: 
      collect: 
      scope: 
      description: 
      condition: 
      on_entry: 
      on_exit: 
      on_error: 
      max_retries: '600'
      max_time: 
  - field:
      aetype: state
      name: CleanImportInstance
      display_name: 
      datatype: string
      priority: 6
      owner: 
      default_value: 
      substitute: true
      message: create
      visibility: 
      collect: 
      scope: 
      description: 
      condition: 
      on_entry: 
      on_exit: 
      on_error: 
      max_retries: '100'
      max_time: 
  - field:
      aetype: state
      name: EmailImportInstance
      display_name: 
      datatype: string
      priority: 7
      owner: 
      default_value: 
      substitute: true
      message: create
      visibility: 
      collect: 
      scope: 
      description: 
      condition: 
      on_entry: 
      on_exit: 
      on_error: 
      max_retries: '100'
      max_time: 
  - field:
      aetype: state
      name: ImportVolume
      display_name: 
      datatype: string
      priority: 8
      owner: 
      default_value: 
      substitute: true
      message: create
      visibility: 
      collect: 
      scope: 
      description: 
      condition: 
      on_entry: 
      on_exit: 
      on_error: 
      max_retries: '100'
      max_time: 
  - field:
      aetype: state
      name: CheckImportVolume
      display_name: 
      datatype: string
      priority: 9
      owner: 
      default_value: 
      substitute: true
      message: create
      visibility: 
      collect: 
      scope: 
      description: 
      condition: 
      on_entry: 
      on_exit: 
      on_error: 
      max_retries: '600'
      max_time: 
  - field:
      aetype: state
      name: CleanImportVolume
      display_name: 
      datatype: string
      priority: 10
      owner: 
      default_value: 
      substitute: true
      message: create
      visibility: 
      collect: 
      scope: 
      description: 
      condition: 
      on_entry: 
      on_exit: 
      on_error: 
      max_retries: '100'
      max_time: 
  - field:
      aetype: state
      name: EmailImportVolume
      display_name: 
      datatype: string
      priority: 11
      owner: 
      default_value: 
      substitute: true
      message: create
      visibility: 
      collect: 
      scope: 
      description: 
      condition: 
      on_entry: 
      on_exit: 
      on_error: 
      max_retries: '100'
      max_time: 
  - field:
      aetype: state
      name: AttachVolume
      display_name: 
      datatype: string
      priority: 12
      owner: 
      default_value: 
      substitute: true
      message: create
      visibility: 
      collect: 
      scope: 
      description: 
      condition: 
      on_entry: 
      on_exit: 
      on_error: 
      max_retries: '100'
      max_time: 
  - field:
      aetype: state
      name: CheckAttachVolume
      display_name: 
      datatype: string
      priority: 13
      owner: 
      default_value: 
      substitute: true
      message: create
      visibility: 
      collect: 
      scope: 
      description: 
      condition: 
      on_entry: 
      on_exit: 
      on_error: 
      max_retries: '100'
      max_time: 
  - field:
      aetype: state
      name: SetSecurityGroup
      display_name: 
      datatype: string
      priority: 14
      owner: 
      default_value: 
      substitute: true
      message: create
      visibility: 
      collect: 
      scope: 
      description: 
      condition: 
      on_entry: 
      on_exit: 
      on_error: 
      max_retries: '100'
      max_time: 
  - field:
      aetype: state
      name: SetAWSTags
      display_name: 
      datatype: string
      priority: 15
      owner: 
      default_value: 
      substitute: true
      message: create
      visibility: 
      collect: 
      scope: 
      description: 
      condition: 
      on_entry: 
      on_exit: 
      on_error: 
      max_retries: '100'
      max_time: 
  - field:
      aetype: state
      name: SetJCDTags
      display_name: 
      datatype: string
      priority: 16
      owner: 
      default_value: 
      substitute: true
      message: create
      visibility: 
      collect: 
      scope: 
      description: 
      condition: 
      on_entry: 
      on_exit: 
      on_error: 
      max_retries: '100'
      max_time: 
  - field:
      aetype: state
      name: EmailOwner
      display_name: 
      datatype: string
      priority: 17
      owner: 
      default_value: /Infrastructure/VM/Migrate/Email/vm_migration_complete?event=vm_migrated
      substitute: true
      message: create
      visibility: 
      collect: 
      scope: 
      description: 
      condition: 
      on_entry: ''
      on_exit: ''
      on_error: ''
      max_retries: '100'
      max_time: 
