---
object_type: class
version: 1.0
object:
  attributes:
    description: 
    display_name: 
    name: Methods
    type: 
    inherits: 
    visibility: 
    owner: 
  schema:
  - field:
      aetype: attribute
      name: migrate_host
      display_name: 
      datatype: string
      priority: 1
      owner: 
      default_value: 10.210.110.8
      substitute: true
      message: create
      visibility: 
      collect: migrate_host = migrate_host
      scope: 
      description: 
      condition: 
      on_entry: 
      on_exit: 
      on_error: 
      max_retries: 
      max_time: 
  - field:
      aetype: attribute
      name: migrate_user
      display_name: 
      datatype: string
      priority: 2
      owner: 
      default_value: root
      substitute: true
      message: create
      visibility: 
      collect: migrate_user = migrate_user
      scope: 
      description: 
      condition: 
      on_entry: 
      on_exit: 
      on_error: 
      max_retries: 
      max_time: 
  - field:
      aetype: method
      name: execute
      display_name: 
      datatype: string
      priority: 3
      owner: 
      default_value: 
      substitute: true
      message: create
      visibility: 
      collect: 
      scope: 
      description: 
      condition: 
      on_entry: 
      on_exit: 
      on_error: 
      max_retries: 
      max_time: 
